### ISSUE TITLE
Can't build with Strawberry Perl 5.28

### ISSUE THREAD

**Issue by thrd92** [benkasminbullock/image-png-qrcode#3]
While Image::PNG::Libpng compiled successfully, Image::PNG::QRCode fails, because can't find necessary libraries (libpng). Inspected the CheckForLibPng.pm. This module in usage by both projects for the same task.
At the same time these modules are different.
1) https://metacpan.org/source/BKB/Image-PNG-Libpng-0.46/inc/CheckForLibPng.pm#L178
2) https://metacpan.org/source/BKB/Image-PNG-QRCode-0.09/inc/CheckForLibPng.pm#L178
UPD: Successfully compiled using CheckForLibPng.pm module from Image::PNG::Libpng

**Comment by benkasminbullock** [comment]
Thanks for your bug report. I've updated the qr code module and put a new
version on cpan.

Please let me know if it doesn't work.
